run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - unconvert
  disable:
    - errcheck

linters-settings:
  revive:
    # Disable unused parameter checks for now to avoid noise
    rules:
      - name: unused-parameter
        disabled: true

issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  max-same-issues: 0
  
  # Excluding configuration per-path and per-linter
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gosec

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true