env:
  - GO111MODULE=auto

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w

universal_binaries:
  - replace: false

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^Merge pull request"
      - "^Merge branch"

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*

brews:
  - repository:
      owner: gitrgoliveira
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    goarm: "7"
    homepage: https://github.com/gitrgoliveira/bracket-creator
    description: A tournament bracket creator
    license: Apache 2.0
    test: |
      system "#{bin}/bracket-creator version"
    dependencies:
      - name: go
        type: optional
    install: |-
      bin.install "bracket-creator"
      bash_completion.install "completions/bracket-creator.bash" => "bracket-creator"
      zsh_completion.install "completions/bracket-creator.zsh" => "_bracket-creator"
      fish_completion.install "completions/bracket-creator.fish"
      man1.install "manpages/bracket-creator.1.gz"

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: https://github.com/gitrgoliveira/bracket-creator
    description: A tournament bracket creator
    maintainer: Thibault HAZELART <gitrgoliveira@gmail.com>
    license: Apache 2.0
    vendor: gitrgoliveira
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/bracket-creator.bash
        dst: /usr/share/bash-completion/completions/bracket-creator
        file_info:
          mode: 0644
      - src: ./completions/bracket-creator.fish
        dst: /usr/share/fish/vendor_completions.d/bracket-creator.fish
        file_info:
          mode: 0644
      - src: ./completions/bracket-creator.zsh
        dst: /usr/share/zsh/vendor-completions/_bracket-creator
        file_info:
          mode: 0644
      - src: ./manpages/bracket-creator.1.gz
        dst: /usr/share/man/man1/bracket-creator.1.gz
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/bracket-creator/copyright
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    recommends:
      - golang
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

# publishers:
#   - name: fury.io
#     ids:
#       - packages
#     env:
#       - "FURY_TOKEN={{ .Env.FURY_TOKEN }}"
#     cmd: ./scripts/fury-upload.sh {{ .ArtifactName }}

release:
  footer: |
    **Full Changelog**: https://github.com/gitrgoliveira/bracket-creator/compare/{{ .PreviousTag }}...{{ .Tag }}
