package state

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// poolMatchesGolden is the EXACT on-disk pool-matches.csv the store writes for
// the two matches below: one with every persisted field non-zero (including a
// hantei, which rides as the mark in the winner's score cell, and an encho,
// which collapses to its period count) and one freshly scheduled with zero
// values everywhere else.
//
// Column position is the on-disk contract (files written by older builds must
// keep loading, and files written now must load in older builds up to their
// column count), so this golden pins the whole format: header wording, column
// order, and every value encoding. It was generated by the writer as it stood
// BEFORE savePoolMatchesLocked/parsePoolMatchesRecords were derived from the
// poolMatchColumns table, so it also proves that refactor changed nothing on
// disk. If this test fails you have changed the file format: that is only
// correct for a NEW APPENDED column, in which case regenerate the tail here
// and say so in the commit.
const poolMatchesGolden = `PoolName,MatchIdx,SideA,SideB,Winner,IpponsA,IpponsB,HansokuA,HansokuB,Decision,Status,Court,SubResults,ScheduledAt,ResultSource,Round,SideAID,SideBID,WinnerID,CorrectionReason,RepPlayerA,RepPlayerB,FlagsA,FlagsB,ReopenPending,DecisionBy,DecisionReason,Encho,ModifiedAt
Pool A,1,Kyoto,Osaka,Kyoto,M|Ht,K,1,2,fought,completed,B,"[{""position"":1,""sideA"":""K1"",""sideB"":""O1"",""ipponsA"":[""D""],""ipponsB"":null,""hansokuA"":0,""hansokuB"":0,""winner"":""K1"",""decision"":""""}]",09:45,admin,3,id-a,id-b,id-a,scoreboard misread,Rep A,Rep B,2,1,true,Referee Tanaka,call recorded,2,1737000000000
Pool B,2,Nara,Kobe,,,,0,0,,scheduled,A,,10:15,,0,,,,,,,0,0,false,,,0,0
`

func poolMatchesGoldenInput() []MatchResult {
	return []MatchResult{
		{
			ID: "Pool A-1", SideA: "Kyoto", SideB: "Osaka", Winner: "Kyoto",
			SideAID: "id-a", SideBID: "id-b", WinnerID: "id-a",
			IpponsA: []string{"M"}, IpponsB: []string{"K"},
			HansokuA: 1, HansokuB: 2,
			Decision: "fought", DecisionBy: "Referee Tanaka", DecisionReason: "call recorded",
			Status: MatchStatusCompleted, Court: "B", Round: 3,
			ScheduledAt: "09:45",
			SubResults: []SubMatchResult{{
				Position: 1, SideA: "K1", SideB: "O1", IpponsA: []string{"D"}, Winner: "K1",
			}},
			Encho:            &EnchoMetadata{PeriodCount: 2},
			DecidedByHantei:  HanteiPtr(true),
			ResultSource:     "admin",
			CorrectionReason: "scoreboard misread",
			RepPlayerA:       "Rep A", RepPlayerB: "Rep B",
			FlagsA: 2, FlagsB: 1,
			ReopenPending: true,
			ModifiedAt:    1737000000000,
		},
		{
			ID: "Pool B-2", SideA: "Nara", SideB: "Kobe",
			Status: MatchStatusScheduled, Court: "A",
			ScheduledAt: "10:15",
		},
	}
}

// TestPoolMatchesGoldenBytes pins the byte-exact file format.
func TestPoolMatchesGoldenBytes(t *testing.T) {
	dir := t.TempDir()
	s, err := NewStore(dir)
	require.NoError(t, err)
	require.NoError(t, s.SaveCompetition(&Competition{ID: "c", Name: "C"}))

	require.NoError(t, s.SavePoolMatches("c", poolMatchesGoldenInput()))
	b, err := os.ReadFile(filepath.Join(dir, "competitions", "c", "pool-matches.csv"))
	require.NoError(t, err)
	assert.Equal(t, poolMatchesGolden, string(b),
		"pool-matches.csv bytes changed; column position is the on-disk contract")
}

// TestPoolMatchesGoldenLoads proves the pinned bytes load back into the same
// results a fresh save would produce, closing the loop from the READ side: a
// reader change that silently reinterprets an existing column fails here even
// if the writer still emits identical bytes.
func TestPoolMatchesGoldenLoads(t *testing.T) {
	dir := t.TempDir()
	s, err := NewStore(dir)
	require.NoError(t, err)
	require.NoError(t, s.SaveCompetition(&Competition{ID: "c", Name: "C"}))
	require.NoError(t, s.atomicWrite(s.compPath("c", "pool-matches.csv"), []byte(poolMatchesGolden), 0600))

	fresh, err := NewStore(dir)
	require.NoError(t, err)
	loaded, err := fresh.LoadPoolMatches("c")
	require.NoError(t, err)
	require.Len(t, loaded, 2)

	want := poolMatchesGoldenInput()
	// Normalise the two encoding-level asymmetries the round trip is allowed:
	// a nil ippon slice loads as the empty slice (splitIppons of ""), and the
	// sub-result's nil IpponsB comes back nil through JSON.
	want[1].IpponsA, want[1].IpponsB = []string{}, []string{}
	assert.Equal(t, want[0], loaded[0])
	assert.Equal(t, want[1], loaded[1])
}
