// Package engine — daihyosen (representative-bout) play-off for tied
// knockout-stage team matches.
//
// Daihyosen is the FIK tie-breaker for knockout team matches that end
// with both teams equal on Individual Victories (IV) AND Points Won
// (PW). Each team sends ONE representative competitor who plays a
// single one-ippon bout to decide the winner — there are no further
// fall-backs once daihyosen is reached.
//
// FR-046, data-model §1, CHK026.
package engine

import (
	"errors"
	"strings"

	"github.com/gitrgoliveira/bracket-creator/internal/domain"
	"github.com/gitrgoliveira/bracket-creator/internal/state"
)

// ErrNotTied is returned by AddDaihyosen when the two TeamSummary
// values differ on either IV or PW. Callers map this to HTTP 400
// ("not_tied") — the operator must score the match normally instead.
var ErrNotTied = errors.New("daihyosen requires a tied IV+PW result")

// ErrPoolMatch is returned by AddDaihyosen when the target match is a
// pool-stage match. Pool matches are allowed to end in hikiwake
// (drawn); daihyosen is reserved for knockout-stage matches that must
// produce a single winner. Callers map this to HTTP 400 ("pool_match").
var ErrPoolMatch = errors.New("daihyosen is only valid in knockout matches")

// ErrInsufficientEligibility is returned by AddDaihyosen when one or
// both teams have zero eligible competitors remaining (every roster
// member has kiken'd or otherwise been marked ineligible). Callers map
// this to HTTP 409 ("insufficient_eligibility") and MUST then record
// the match result with the opposing team as Winner — per CHK026, a
// team unable to field a representative forfeits the encounter.
var ErrInsufficientEligibility = errors.New("daihyosen requires at least one eligible competitor per side")

// TeamSummary captures the two tie-breaker metrics relevant to the
// daihyosen decision. Fields mirror the corresponding state.PlayerStanding
// columns produced by computeStandings — callers building this from a
// completed team-match's SubResults can do so directly without going
// through the standings cache (see ComputeTeamSummary).
//
// FR-046, data-model §1.
type TeamSummary struct {
	// IndividualWins is the count of sub-bouts the team won outright
	// (IV in the team scoreline). Draws do NOT contribute here.
	IndividualWins int
	// PointsWon is the total number of ippons the team scored across
	// all sub-bouts (PW in the team scoreline). Hansoku-derived ippons
	// follow whichever side they were credited to in the sub-result.
	PointsWon int
}

// IsTied reports whether two TeamSummary values match on both IV and
// PW. This is the trigger condition for daihyosen — a team match that
// otherwise has a decided IV winner does NOT require daihyosen even
// when PW is equal.
func IsTied(a, b TeamSummary) bool {
	return a.IndividualWins == b.IndividualWins && a.PointsWon == b.PointsWon
}

// IsPoolMatchID reports whether a match ID belongs to the pool stage.
// Pool match IDs follow the "<PoolName>-<idx>" convention generated by
// helper.CreatePoolMatches (e.g. "Pool A-0", "Pool B-3"). Bracket match
// IDs use a different shape ("r1-m0", numeric, or other). Centralising
// this distinction here lets handlers call AddDaihyosen without
// duplicating the prefix check.
func IsPoolMatchID(matchID string) bool {
	return strings.HasPrefix(matchID, "Pool ")
}

// ComputeTeamSummary aggregates SubMatchResult entries into TeamSummary
// values for the two named sides. Sub-results whose Winner is empty
// (drawn bouts / hikiwake) contribute nothing to IV but their ippons
// still count toward PW for whichever side scored them.
//
// SideA/SideB names are matched against sub.Winner using the same
// fallback as computeStandings (sub.Winner may carry either the
// match-level side name or the sub-result-level side name).
//
// Pass the names from the parent MatchResult.SideA / SideB so the
// caller's view of "left team" / "right team" is canonical.
func ComputeTeamSummary(subResults []state.SubMatchResult, sideAName, sideBName string) (TeamSummary, TeamSummary) {
	var a, b TeamSummary
	for _, sub := range subResults {
		// Skip the daihyosen placeholder itself (Position == -1) so a
		// previously-added daihyosen bout doesn't double-count when an
		// operator re-validates the tie.
		if sub.Position < 0 {
			continue
		}
		sideAWin := sub.Winner == sideAName || sub.Winner == sub.SideA
		sideBWin := sub.Winner == sideBName || sub.Winner == sub.SideB
		switch {
		case sideAWin:
			a.IndividualWins++
		case sideBWin:
			b.IndividualWins++
		}
		// PW counts every ippon scored regardless of bout outcome —
		// hikiwake bouts where both sides scored still contribute.
		a.PointsWon += len(sub.IpponsA)
		b.PointsWon += len(sub.IpponsB)
	}
	return a, b
}

// AddDaihyosen validates the request to add a daihyosen bout to a team
// match and returns a SubMatchResult placeholder that the operator
// fills in via the standard score path.
//
// Validation order (matches handler 400 vs 409 mapping):
//
//  1. ErrPoolMatch when isPool — daihyosen is knockout-only.
//  2. ErrNotTied when IV or PW differ — operator must score normally.
//  3. ErrInsufficientEligibility when either side has 0 eligible
//     competitors — caller MUST then record a match result with the
//     opposing team as Winner (CHK026 forfeit rule).
//
// The returned SubMatchResult has Position = -1 (a sentinel for "this
// is a daihyosen bout, not a numbered roster position") and
// Decision = "daihyosen". The handler appends this to the match's
// SubResults; the operator subsequently records the rep players +
// ippon via the score modal.
//
// CHK026: when a team has exactly 1 eligible competitor, that
// competitor MUST be the rep — the operator selects them in the score
// modal. The engine does not enforce that single-choice constraint
// here (it has no view of the lineup); it only guarantees at least
// one option exists per side.
//
// FR-046, CHK026, T139.
func (e *Engine) AddDaihyosen(
	compID, matchID string,
	sideA, sideB TeamSummary,
	isPool bool,
	sideAEligible, sideBEligible int,
) (*state.SubMatchResult, error) {
	if isPool {
		return nil, ErrPoolMatch
	}
	if !IsTied(sideA, sideB) {
		return nil, ErrNotTied
	}
	if sideAEligible == 0 || sideBEligible == 0 {
		return nil, ErrInsufficientEligibility
	}
	return &state.SubMatchResult{
		Position: -1, // sentinel: daihyosen, not a numbered roster bout
		Decision: string(domain.DecisionDaihyosen),
	}, nil
}
