// Package engine, daihyosen (representative-bout) tie-breaker for tied
// knockout-stage team matches.
//
// Daihyosen is the FIK tie-breaker for knockout team matches that end
// with both teams equal on Individual Victories (IV) AND Points Won
// (PW). Each team sends ONE representative competitor who plays a
// single one-ippon bout to decide the winner, there are no further
// fall-backs once daihyosen is reached.
//
// FR-046, data-model §1, CHK026.
package engine

import (
	"errors"
	"fmt"
	"strings"

	"github.com/gitrgoliveira/bracket-creator/internal/domain"
	"github.com/gitrgoliveira/bracket-creator/internal/state"
)

// ErrNotTied is returned by AddDaihyosen when the two TeamSummary
// values differ on either IV or PW. Callers map this to HTTP 400
// ("not_tied"), the operator must score the match normally instead.
var ErrNotTied = errors.New("daihyosen requires a tied IV+PW result")

// ErrPoolMatch is returned by AddDaihyosen when the target match is a
// pool-stage match. Pool matches are allowed to end in hikiwake
// (drawn); daihyosen is reserved for knockout-stage matches that must
// produce a single winner. Callers map this to HTTP 400 ("pool_match").
var ErrPoolMatch = errors.New("daihyosen is only valid in knockout matches")

// ErrInsufficientEligibility is returned by AddDaihyosen when one or
// both teams have zero eligible competitors remaining (every roster
// member has kiken'd or otherwise been marked ineligible). Callers map
// this to HTTP 409 ("insufficient_eligibility") and MUST then record
// the match result with the opposing team as Winner, per CHK026, a
// team unable to field a representative forfeits the encounter.
var ErrInsufficientEligibility = errors.New("daihyosen requires at least one eligible competitor per side")

// TeamSummary captures the two tie-breaker metrics relevant to the
// daihyosen decision. Fields mirror the corresponding state.PlayerStanding
// columns produced by computeStandings, callers building this from a
// completed team-match's SubResults can do so directly without going
// through the standings cache (see ComputeTeamSummary).
//
// FR-046, data-model §1.
type TeamSummary struct {
	// IndividualWins is the count of sub-bouts the team won outright
	// (IV in the team scoreline). Draws do NOT contribute here.
	IndividualWins int
	// PointsWon is the total number of ippons the team scored across
	// all sub-bouts (PW in the team scoreline). Hansoku-derived ippons
	// follow whichever side they were credited to in the sub-result.
	PointsWon int
}

// IsTied reports whether two TeamSummary values match on both IV and
// PW. This is the trigger condition for daihyosen, a team match that
// otherwise has a decided IV winner does NOT require daihyosen even
// when PW is equal.
func IsTied(a, b TeamSummary) bool {
	return a.IndividualWins == b.IndividualWins && a.PointsWon == b.PointsWon
}

// IsPoolMatchID reports whether a match ID belongs to the pool stage.
// Pool match IDs follow the "<PoolName>-<idx>" convention generated by
// helper.CreatePoolMatches (e.g. "Pool A-0", "Pool B-3"). Bracket match
// IDs use a different shape ("r1-m0", numeric, or other). Centralising
// this distinction here lets handlers call AddDaihyosen without
// duplicating the prefix check.
func IsPoolMatchID(matchID string) bool {
	return strings.HasPrefix(matchID, "Pool ")
}

// poolNameFromMatchID extracts the pool name from a pool match ID by
// stripping the trailing DH, TB, or plain numeric suffix. This is
// unambiguous regardless of hyphens in the pool name and avoids the
// ambiguity of prefix-scanning against a map of known pool names.
//
// Examples:
//
//	"Pool A-DH-0"      → "Pool A"
//	"Pool A-East-TB-2" → "Pool A-East"
//	"Pool A-0"         → "Pool A"
func poolNameFromMatchID(id string) (string, bool) {
	if i := strings.LastIndex(id, "-DH-"); i > 0 {
		return id[:i], true
	}
	if i := strings.LastIndex(id, "-TB-"); i > 0 {
		return id[:i], true
	}
	// Plain pool match: strip trailing "-<digits>".
	if i := strings.LastIndexByte(id, '-'); i > 0 {
		suffix := id[i+1:]
		allDigits := len(suffix) > 0
		for _, c := range suffix {
			if c < '0' || c > '9' {
				allDigits = false
				break
			}
		}
		if allDigits {
			return id[:i], true
		}
	}
	return "", false
}

// IsPoolDaihyosenMatchID reports whether a match ID is a pool-stage
// daihyosen bout (IDs of the form "Pool X-DH-N"). These are generated
// by InjectPoolDaihyosenMatches when all team-pool matches complete with
// a tie on all 8 ranking criteria. They are structurally pool matches
// but scored as individual (one representative per side) rather than as
// full team bouts.
func IsPoolDaihyosenMatchID(matchID string) bool {
	return strings.Contains(matchID, "-DH-")
}

// generatePoolDaihyosenMatches creates round-robin MatchResult entries for
// a tied group of teams in team-pool competitions. Mirrors
// generateTiebreakerMatches but uses the "DH-N" ID prefix and is used when
// teams are fully tied on all 8 ranking criteria after regular pool play.
func generatePoolDaihyosenMatches(poolName string, tiedGroup []state.PlayerStanding, existingDHCount int, court string, existingPairs map[string]bool) []state.MatchResult {
	var results []state.MatchResult
	idx := existingDHCount
	for _, a := range tiedGroup {
		for _, b := range tiedGroup {
			if a.Player.Name >= b.Player.Name {
				continue // only generate each pair once (a < b alphabetically)
			}
			key := tiebreakerPairKey(a.Player.Name, b.Player.Name)
			if existingPairs[key] {
				continue
			}
			results = append(results, state.MatchResult{
				ID:     fmt.Sprintf("%s-DH-%d", poolName, idx),
				SideA:  a.Player.Name,
				SideB:  b.Player.Name,
				Status: state.MatchStatusScheduled,
				Court:  court,
			})
			existingPairs[key] = true
			idx++
		}
	}
	return results
}

// InjectPoolDaihyosenMatches inspects team-pool standings for compID after
// all regular pool matches are complete. For every tied group (same weighted
// Points encoding all 8 ranking criteria), it generates a round-robin of
// daihyosen (representative) bouts, appends them to the pool-matches store,
// and regenerates the schedule. Returns the newly injected matches (nil when
// there are no ties or all DH pairs already exist).
//
// Pool-DH match IDs use the "Pool X-DH-N" format. They are scored as
// individual (one representative per side) rather than as full team bouts;
// their results are applied to standings via the DH secondary sort in
// computeStandings. The frontend routes these to the individual ScoreEditorModal
// by detecting the DH prefix in compMatches.
func (e *Engine) InjectPoolDaihyosenMatches(compID string) ([]state.MatchResult, error) {
	comp, err := e.store.LoadCompetition(compID)
	if err != nil {
		return nil, err
	}
	if comp == nil {
		return nil, notFoundErrorf("competition %s not found", compID)
	}

	// A daihyosen is played only where the tie affects advancement/seeding
	// (see tieAffectsAdvancement): the top poolWinners of each pool advance.
	poolWinners := comp.EffectivePoolWinners()

	standings, err := e.CalculatePoolStandings(compID)
	if err != nil {
		return nil, err
	}

	allMatches, err := e.store.LoadPoolMatches(compID)
	if err != nil {
		return nil, err
	}

	// Scan existing DH matches per pool for idempotency and ID sequencing.
	// poolNameFromMatchID strips the trailing suffix deterministically so
	// overlapping pool names (e.g. "Pool A" vs "Pool A-East") are handled
	// correctly without ambiguous prefix scanning.
	type poolDHInfo struct {
		existingPairs map[string]bool
		count         int
	}
	poolDH := map[string]*poolDHInfo{}
	poolCourt := map[string]string{}
	// regularIncomplete[pool] is true if any regular (non-DH) match in the pool
	// is not yet completed. Daihyosen tie-breaks must only be injected after a
	// pool's regular round-robin is finished, otherwise a partial-result tie
	// would inject DH matches that a later result breaks, orphaning them. (See
	// the matching guard in InjectTiebreakerMatches.)
	regularIncomplete := map[string]bool{}
	for _, m := range allMatches {
		pn, ok := poolNameFromMatchID(m.ID)
		if !ok {
			continue
		}
		if _, inStandings := standings[pn]; !inStandings {
			continue
		}
		if _, seen := poolCourt[pn]; !seen {
			// Uses the first match's court. Pool competitions assign one
			// court per pool, so all matches in a pool share the same court.
			poolCourt[pn] = m.Court
		}
		if IsPoolDaihyosenMatchID(m.ID) {
			if poolDH[pn] == nil {
				poolDH[pn] = &poolDHInfo{existingPairs: map[string]bool{}}
			}
			poolDH[pn].count++
			poolDH[pn].existingPairs[tiebreakerPairKey(m.SideA, m.SideB)] = true
		} else if m.Status != state.MatchStatusCompleted {
			regularIncomplete[pn] = true
		}
	}

	var injected []state.MatchResult
	for poolName, poolStandings := range standings {
		// Don't inject daihyosen until the pool's regular matches are all done.
		if regularIncomplete[poolName] {
			continue
		}
		info := poolDH[poolName]
		existingCount := 0
		existingPairs := map[string]bool{}
		if info != nil {
			existingCount = info.count
			existingPairs = info.existingPairs
		}

		for _, positions := range detectPoolTies(poolStandings) {
			// Only break ties that affect who advances / their seed: a tie sitting
			// entirely below the top-poolWinners cut shares its rank with no bout.
			if !tieAffectsAdvancement(positions, poolWinners) {
				continue
			}
			group := standingsAt(poolStandings, positions)
			newMatches := generatePoolDaihyosenMatches(poolName, group, existingCount, poolCourt[poolName], existingPairs)
			existingCount += len(newMatches)
			injected = append(injected, newMatches...)
		}
	}

	if len(injected) == 0 {
		return nil, nil
	}

	allMatches = append(allMatches, injected...)

	// Reassign slots so the new DH matches get ScheduledAt values.
	existingTimes := make(map[string]string, len(allMatches))
	for _, m := range allMatches {
		if m.ScheduledAt != "" {
			existingTimes[m.ID] = m.ScheduledAt
		}
	}
	tournament, err := e.store.LoadTournament()
	if err != nil {
		return nil, err
	}
	state.ApplyTournamentDefaults(tournament)
	state.ApplyCompetitionDefaults(comp)
	allMatches, _ = assignPoolMatchSlots(allMatches, comp, tournament)
	for i := range allMatches {
		if t, ok := existingTimes[allMatches[i].ID]; ok {
			allMatches[i].ScheduledAt = t
		}
	}

	if err := e.store.SavePoolMatches(compID, allMatches); err != nil {
		return nil, err
	}

	e.standingsCache.Delete(compID)
	e.standingsFlight.Delete(compID)

	return injected, e.GenerateSchedule(compID)
}

// ComputeTeamSummary aggregates SubMatchResult entries into TeamSummary
// values for the two named sides. Sub-results whose Winner is empty
// (drawn bouts / hikiwake) contribute nothing to IV but their ippons
// still count toward PW for whichever side scored them.
//
// SideA/SideB names are matched against sub.Winner using the same
// fallback as computeStandings (sub.Winner may carry either the
// match-level side name or the sub-result-level side name).
//
// Pass the names from the parent MatchResult.SideA / SideB so the
// caller's view of "left team" / "right team" is canonical.
func ComputeTeamSummary(subResults []state.SubMatchResult, sideAName, sideBName string) (TeamSummary, TeamSummary) {
	var a, b TeamSummary
	for _, sub := range subResults {
		// Skip the daihyosen placeholder itself (Position == -1) so a
		// previously-added daihyosen bout doesn't double-count when an
		// operator re-validates the tie.
		if sub.Position < 0 {
			continue
		}
		sideAWin := isWinForSide(sub.Winner, sideAName, sub.SideA)
		sideBWin := isWinForSide(sub.Winner, sideBName, sub.SideB)
		switch {
		case sideAWin:
			a.IndividualWins++
		case sideBWin:
			b.IndividualWins++
		}
		// PW counts every ippon scored regardless of bout outcome,
		// hikiwake bouts where both sides scored still contribute.
		a.PointsWon += len(sub.IpponsA)
		b.PointsWon += len(sub.IpponsB)
	}
	return a, b
}

// AddDaihyosen validates the request to add a daihyosen bout to a team
// match and returns a SubMatchResult placeholder that the operator
// fills in via the standard score path.
//
// Validation order (matches handler 400 vs 409 mapping):
//
//  1. ErrPoolMatch when isPool, daihyosen is knockout-only.
//  2. ErrNotTied when IV or PW differ, operator must score normally.
//  3. ErrInsufficientEligibility when either side has 0 eligible
//     competitors, caller MUST then record a match result with the
//     opposing team as Winner (CHK026 forfeit rule).
//
// The returned SubMatchResult has Position = -1 (a sentinel for "this
// is a daihyosen bout, not a numbered roster position") and
// Decision = "daihyosen". The handler appends this to the match's
// SubResults; the operator subsequently records the rep players +
// ippon via the score modal.
//
// CHK026: when a team has exactly 1 eligible competitor, that
// competitor MUST be the rep, the operator selects them in the score
// modal. The engine does not enforce that single-choice constraint
// here (it has no view of the lineup); it only guarantees at least
// one option exists per side.
//
// FR-046, CHK026, T139.
func (e *Engine) AddDaihyosen(
	compID, matchID string,
	sideA, sideB TeamSummary,
	isPool bool,
	sideAEligible, sideBEligible int,
) (*state.SubMatchResult, error) {
	if isPool {
		return nil, ErrPoolMatch
	}
	if !IsTied(sideA, sideB) {
		return nil, ErrNotTied
	}
	if sideAEligible == 0 || sideBEligible == 0 {
		return nil, ErrInsufficientEligibility
	}
	return &state.SubMatchResult{
		Position: -1, // sentinel: daihyosen, not a numbered roster bout
		Decision: string(domain.DecisionDaihyosen),
	}, nil
}
