package domain_test

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"github.com/gitrgoliveira/bracket-creator/internal/domain"
)

// TestIsValidIpponEntry pins the wire-level predicate against the pool CSV's
// ippon join separator (IpponFieldSeparator, "|"). Before this test's fix,
// the separator is a single rune and passed as a well-formed entry even
// though internal/state's codec (pools.go: splitIppons, poolMatchColumns)
// uses that exact byte to delimit a joined slice — so {"M", "|"} validated,
// persisted as the CSV cell "M||", and reloaded as {"M", "", ""}, silently
// disagreeing with what was validated and broadcast before the round trip.
func TestIsValidIpponEntry(t *testing.T) {
	assert.False(t, domain.IsValidIpponEntry(domain.IpponFieldSeparator),
		"the CSV join separator must never validate as a well-formed ippon entry")
	assert.False(t, domain.IsValidIpponEntry("|"),
		"pinned against the literal byte, independent of the constant's value")

	// Every other previously-legal shape must keep passing: waza letters, the
	// default-win maru, the unfilled-slot placeholder, the hantei mark, and
	// empty.
	for _, v := range []string{"M", "K", "D", "T", "H", "S", "○", domain.IpponPlaceholder, domain.HanteiMark, ""} {
		assert.Truef(t, domain.IsValidIpponEntry(v), "entry %q should remain valid", v)
	}

	// Any other multi-rune string is still rejected (unchanged behaviour).
	assert.False(t, domain.IsValidIpponEntry("MK"))
}

func TestParseScore(t *testing.T) {
	tests := []struct {
		name        string
		in          string
		wantIppons  []string
		wantHansoku int
	}{
		{"empty", "", nil, 0},
		{"one ippon", "M", []string{"M"}, 0},
		{"two ippons", "MK", []string{"M", "K"}, 0},
		{"hansoku only", "(H1)", nil, 1},
		{"ippons and hansoku", "MK (H1)", []string{"M", "K"}, 1},
		{"legacy multi hansoku", "M (H2)", []string{"M"}, 2},
		{"multi-byte maru survives the rune split", "○○", []string{"○", "○"}, 0},
		{"surrounding whitespace", "  MK  ", []string{"M", "K"}, 0},
		{"interior spaces are not ippons", "M K", []string{"M", "K"}, 0},
		// Persisted data on a live path: an unreadable count degrades to 0
		// rather than failing the read and blanking the match.
		{"malformed hansoku count", "M (Hx)", []string{"M"}, 0},
		// Pinning the byte-lookahead rewrite: the mark sits between two bare
		// letters/points, so a wrong skip index would eat or duplicate a
		// neighbour.
		{"mark between two hansoku ippons", "HtH", []string{"Ht", "H"}, 0},
		{"mark sandwiched between points", "MHtM", []string{"M", "Ht", "M"}, 0},
		// Non-ASCII passthrough: a multi-byte maru next to the 'H' lookahead
		// must not desync the byte offsets the lookahead relies on.
		{"maru before a bare hansoku ippon", "○H", []string{"○", "H"}, 0},
		{"bare hansoku ippon before a maru", "H○", []string{"H", "○"}, 0},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			ippons, hansoku := domain.ParseScore(tc.in)
			assert.Equal(t, tc.wantIppons, ippons)
			assert.Equal(t, tc.wantHansoku, hansoku)
		})
	}
}

// TestParseScore_PinnedLegacyBytes pins ParseScore against literal byte
// strings a pre-unification bracket.json can still hold on disk forever
// (state.BracketMatch.ScoreA/ScoreB, folded on load by NormalizeLegacy). This
// used to be a round-trip test against the now-removed FormatScore encode
// half; ParseScore is the only direction still exercised in production, so
// the cases are stated as literal strings rather than generated by encoding
// the expected ippons, but the corpus itself (the hantei mark alone, adjacent
// to a real "H" ippon in both orders, and the hansoku suffix) is unchanged.
func TestParseScore_PinnedLegacyBytes(t *testing.T) {
	cases := []struct {
		encoded string
		ippons  []string
		hansoku int
	}{
		{"", nil, 0},
		{"M", []string{"M"}, 0},
		{"MK", []string{"M", "K"}, 0},
		{"MK (H1)", []string{"M", "K"}, 1},
		{"(H1)", nil, 1},
		{"DT (H2)", []string{"D", "T"}, 2},
		{"○○", []string{"○", "○"}, 0},
		{"H (H1)", []string{"H"}, 1},
		{"S", []string{"S"}, 0},
		// The codec's one two-rune token: the hantei mark, alone, after a
		// point, and adjacent to a real "H" ippon in both orders (the
		// no-lone-"t" lookahead must not eat a neighbouring hansoku letter).
		{"Ht", []string{"Ht"}, 0},
		{"KHt", []string{"K", "Ht"}, 0},
		{"HHt", []string{"H", "Ht"}, 0},
		{"HtH (H1)", []string{"Ht", "H"}, 1},
		{"HtH", []string{"Ht", "H"}, 0},
		{"MHtM", []string{"M", "Ht", "M"}, 0},
	}
	for _, tc := range cases {
		t.Run(tc.encoded, func(t *testing.T) {
			ippons, hansoku := domain.ParseScore(tc.encoded)
			assert.Equal(t, tc.ippons, ippons, "ippons from %q", tc.encoded)
			assert.Equal(t, tc.hansoku, hansoku, "hansoku from %q", tc.encoded)
		})
	}
}
